install.packages('dplyr')
library(dplyr)
packageVersion('dplyr')
# > packageVersion('dplyr')
# [1] ‘0.8.3’

# 259 개 함수 포함
# 190815 기준 77개 사용경험 있음
## 사용해본적 있는 것
sel_val <- names(iris)
iris %>% group_by(sel_val)
iris %>% group_by_(.dots = sel_val)

for (idx in sel_val) {
  iris %>% 
    group_by_(.dots = idx) %>% 
    count() %>% 
    print()
}

# what is difference between group_by and group_by_?
#Dplyr uses non-standard evaluation (NSE) in all of the most important single table verbs: 
# filter(), mutate(), summarise(), arrange(), select() and group_by(). 
# NSE is important not only to save you typing, but for database backends, 
# is what makes it possible to translate your R code to SQL. 
# However, while NSE is great for interactive use it’s hard to program with. 
# This vignette describes how you can opt out of NSE in dplyr, and instead rely only on SE (along with a little quoting).

#Every function in dplyr that uses NSE also has a version that uses SE. 
# There’s a consistent naming scheme: the SE is the NSE name with _ on the end. 
# For example, the SE version of summarise() is summarise_(), the SE version of arrange() is arrange_(). 
# These functions work very similarly to their NSE cousins, but the inputs must be “quoted”

# 기본
dplyr::glimpse()
dplyr::as_tibble()
dplyr::select()
dplyr::filter()
dplyr::group_by()
dplyr::mutate()
dplyr::arrange()
dplyr::distinct()


# 고급

dplyr::arrange_()
dplyr::arrange_all()
dplyr::arrange_at()
dplyr::arrange_if()
dplyr::as_data_frame()
dplyr::collect()
dplyr::distinct_()
dplyr::distinct_all()
dplyr::distinct_at()
dplyr::distinct_if()
dplyr::ends_with()
dplyr::everything()
dplyr::filter_()
dplyr::filter_all()
dplyr::filter_at()
dplyr::filter_if()
dplyr::group_by_()
dplyr::group_by_all()
dplyr::group_by_at()
dplyr::group_by_if()
dplyr::if_else()
dplyr::intersect()
dplyr::lag()
dplyr::lead()
dplyr::mutate_()
dplyr::mutate_all()
dplyr::mutate_at()
dplyr::mutate_each()
dplyr::mutate_each_()
dplyr::mutate_if()
dplyr::n_distinct()
dplyr::n()
dplyr::rename()
dplyr::rename_()
dplyr::sample_frac()
dplyr::sample_n()
dplyr::select_()
dplyr::select_all()
dplyr::select_at()
dplyr::select_if()
dplyr::select_var()
dplyr::select_vars()
dplyr::select_vars_()
dplyr::starts_with()
dplyr::summarise()
dplyr::summarise_()
dplyr::summarize_all()
dplyr::summarize_at()
dplyr::summarize_each()
dplyr::summarize_each_()
dplyr::summarize_if()
dplyr::sym()
dplyr::tibble()
dplyr::transmute()
dplyr::transmute_()
dplyr::transmute_all()
dplyr::transmute_at()
dplyr::transmute_if()
dplyr::tribble()
dplyr::ungroup()
dplyr::union()
dplyr::union_all()
dplyr::coalesce()
dplyr::add_row()


## join
dplyr::semi_join()
dplyr::full_join()
dplyr::inner_join()
dplyr::anti_join()
dplyr::left_join()
dplyr::right_join()
dplyr::nest_join()

## dataset

dplyr::band_instruments
dplyr::band_instruments2
dplyr::band_members
dplyr::nasa
dplyr::starwars
dplyr::storms

## windowed rank function
dplyr::cume_dist()
dplyr::row_number()
dplyr::ntile()
dplyr::min_rank()
dplyr::dense_rank()
dplyr::percent_rank()


## Count/tally observations by group
dplyr::add_count()
dplyr::add_count_()
dplyr::add_tally()
dplyr::add_tally_()
dplyr::count()
dplyr::count_()
dplyr::tally()
dplyr::tally_()

## Apply predicate to all variables
dplyr::all_vars()
dplyr::any_vars()

## structure

## 처음 보는 것

dplyr::add_rownames()
dplyr::all_equal()

dplyr::as_label()
dplyr::as.tbl()
dplyr::as.tbl_cube()
dplyr::auto_copy()
dplyr::bench_tbls()
dplyr::between()
dplyr::bind_cols()
dplyr::bind_rows()
dplyr::case_when()
dplyr::changes()
dplyr::check_dbplyr()
dplyr::collapse()
dplyr::combine()
dplyr::common_by()
dplyr::compare_tbls()
dplyr::compare_tbls2()
dplyr::compute()
dplyr::contains()
dplyr::copy_to()
dplyr::cumall()
dplyr::cumany()
dplyr::cummean()
dplyr::current_vars()
dplyr::data_frame()
dplyr::data_frame_()
dplyr::db_analyze()
dplyr::db_begin()
dplyr::db_commit()
dplyr::db_create_index()
dplyr::db_create_indexes()
dplyr::db_create_table()
dplyr::db_data_type()
dplyr::db_desc()
dplyr::db_drop_table()
dplyr::db_explain()
dplyr::db_has_table()
dplyr::db_insert_into()
dplyr::db_list_tables()
dplyr::db_query_fields()
dplyr::db_query_rows()
dplyr::db_rollback()
dplyr::db_save_query()
dplyr::db_write_table()
dplyr::desc()
dplyr::dim_desc()
dplyr::distinct_prepare()
dplyr::do()
dplyr::do_()
dplyr::dr_dplyr()
dplyr::enexpr()
dplyr::enexprs()
dplyr::enquo()
dplyr::enquos()
dplyr::ensym()
dplyr::ensyms()
dplyr::eval_tbls()
dplyr::eval_tbls2()
dplyr::explain()
dplyr::expr()
dplyr::failwith()
dplyr::first()
dplyr::frame_data()
dplyr::funs()
dplyr::funs_()
dplyr::group_by_drop_default()
dplyr::group_by_prepare()
dplyr::group_cols()
dplyr::group_data()
dplyr::group_indices()
dplyr::group_indices_()
dplyr::group_keys()
dplyr::group_map()
dplyr::group_modify()
dplyr::group_nest()
dplyr::group_rows()
dplyr::group_size()
dplyr::group_split()
dplyr::group_trim()
dplyr::group_vars()
dplyr::group_walk()
dplyr::grouped_df()
dplyr::groups()
dplyr::hybrid_call()
dplyr::id()
dplyr::ident()
dplyr::is_grouped_df()
dplyr::is.grouped_df()
dplyr::is.src()
dplyr::is.tbl()
dplyr::last()
dplyr::last_col()
dplyr::location()
dplyr::lst()
dplyr::lst_()
dplyr::make_tbl()
dplyr::matches()
dplyr::n_groups()
dplyr::na_if()
dplyr::near()
dplyr::new_grouped_df()
dplyr::nth()
dplyr::num_range()
dplyr::one_of()
dplyr::order_by()
dplyr::progress_estimated()
dplyr::pull()
dplyr::quo()
dplyr::quo_name()
dplyr::quos()
dplyr::rbind_all()
dplyr::rbind_list()
dplyr::recode()
dplyr::recode_factor()
dplyr::rename_all()
dplyr::rename_at()
dplyr::rename_vars()
dplyr::rename_vars_()
dplyr::rowwise()
dplyr::same_src()
dplyr::setdiff()
dplyr::setequal()
dplyr::show_query()
dplyr::slice()
dplyr::slice_()
dplyr::sql()
dplyr::sql_escape_ident()
dplyr::sql_escape_string()
dplyr::sql_join()
dplyr::sql_select()
dplyr::sql_semi_join()
dplyr::sql_set_op()
dplyr::sql_subquery()
dplyr::sql_translate_env()
dplyr::src()
dplyr::src_df()
dplyr::src_local()
dplyr::src_mysql()
dplyr::src_postgres()
dplyr::src_sqlite()
dplyr::src_tbls()
dplyr::syms()
dplyr::tbl()
dplyr::tbl_cube()
dplyr::tbl_df()
dplyr::tbl_nongroup_vars()
dplyr::tbl_sum()
dplyr::tbl_vars()
dplyr::top_frac()
dplyr::top_n()
dplyr::trunc_mat()
dplyr::type_sum()
dplyr::validate_grouped_df()
dplyr::vars()
dplyr::with_order()
dplyr::wrap_dbplyr_obj()
dplyr::`%>%`()

